### ISSUE TITLE
including server-side validation like asp.net mvc

### ISSUE THREAD

**Issue by ghost** [play-components/play-jqvalidate#1]
Hi,
The optimal solution is using only one validation for both server and client side like asp.net mvc. So, if javascript is disabled on the browser side the user should see the same message (by server validation after postback) as jquery validation.

**Comment by mmurray** [comment]
This solution does only use one validation for both server and client side. It uses Messages.get so even your internationalized validation messages will be used. The demo app didn't really show that because the form didn't actually post anywhere, I just updated it so if you turn javascript off and view the demo it will still have the same validation messages. The source in /samples-and-tests/ is also updated.

**Comment by ghost** [comment]
Perfect!
